apiVersion: v1
kind: Pod
metadata:
  name: gpu-test2
spec:
  runtimeClassName: nvidia
  containers:
  - name: cuda
    image: easzlab.io.local:5000/nvidia/pytorch:25.09-py3
    command: ["nvidia-smi"]
    resources:
      limits:
        nvidia.com/gpu: 1
  restartPolicy: Never

