apiVersion: kueue.x-k8s.io/v1beta2
kind: ClusterQueue
metadata:
   name: "cluster-queue"
spec:
  namespaceSelector: {}
  resourceGroups:
   - coveredResources: ["cpu", "memory", "pods"]
     flavors:
       - name: on-demand
         resources:
           - name: "cpu"
             nominalQuota: 4
           - name: "memory"
             nominalQuota: 8Gi
           - name: "pods"
             nominalQuota: 5
