# CNCF Kubernetes AI Conformance Submission
# Kubernetes Version: v1.35

metadata:
  kubernetesVersion: v1.33
  platformName: "Taichu Kubernetes Service"
  platformVersion: "v1.12.0"
  vendorName: "Xi'an TieKe Jingwei Information Technology Co.,Ltd."
  website_url: "https://www.rails.cn/xian/en-us/src/prointroduce/kmpp"
  repo_url: "https://github.com/mensylisir/taichu-ai"
  documentation_url: "https://github.com/mensylisir/taichu-ai/tree/master/docs"
  product_logo_url: "https://www.rails.cn/xian/assets/static/logo1.179003c.2b0dfa30eeb2a44c4d53445a8da814de.svg"
  description: "TaiChu kubernetes engine provie an easier,powerful platform that helps enterprise to use Kubernetes faster and better, include but not limited to installation and maintenance of k8s, deployment, monitoring and management of containerized applications,etc."
  contact_email_address: "whoisfisher@163.com"

spec:
  accelerators:
    - id: dra_support
      description: "Support Dynamic Resource Allocation (DRA) APIs to enable more flexible and fine-grained resource requests beyond simple counts."
      level: MUST
      status: "Implemented"
      evidence:
        - "https://github.com/mensylisir/taichu-ai/blob/master/docs/dra_support.md"
      notes: "DRA API is enabled in Kubernetes 1.34 by default"

  networking:
    - id: ai_inference
      description: "Support the Kubernetes Gateway API with an implementation for advanced traffic management for inference services, which enables capabilities like weighted traffic splitting, header-based routing (for OpenAI protocol headers), and optional integration with service meshes."
      level: MUST
      status: "Implemented"
      evidence:
        - "https://github.com/mensylisir/taichu-ai/blob/master/docs/ai_inference.md"
      notes: ""

  schedulingOrchestration:
    - id: gang_scheduling
      description: "The platform must allow for the installation and successful operation of at least one gang scheduling solution that ensures all-or-nothing scheduling for distributed AI workloads (e.g. Kueue, Volcano, etc.)"
      level: MUST
      status: "Implemented"
      evidence:
        - "https://github.com/mensylisir/taichu-ai/blob/master/docs/gang_scheduling.md"
      notes: ""

    - id: cluster_autoscaling
      description: "If the platform provides a cluster autoscaler or an equivalent mechanism, it must be able to scale up/down node groups containing specific accelerator types based on pending pods requesting those accelerators."
      level: MUST
      status: "N/A"
      evidence:
        - "https://github.com/mensylisir/taichu-ai/blob/master/docs/cluster_autoscaling.md"
      notes: ""

    - id: pod_autoscaling
      description: "If the platform supports the HorizontalPodAutoscaler, it must function correctly for pods utilizing accelerators. This includes the ability to scale these Pods based on custom metrics relevant to AI/ML workloads."
      level: MUST
      status: "N/A"
      evidence:
        - "https://github.com/mensylisir/taichu-ai/blob/master/docs/pod_autoscaling.md"
      notes: ""

  observability:
    - id: accelerator_metrics
      description: "For supported accelerator types, the platform must allow for the installation and successful operation of at least one accelerator metrics solution that exposes fine-grained performance metrics via a standardized, machine-readable metrics endpoint."
      level: MUST
      status: "Implemented"
      evidence:
        - "https://github.com/mensylisir/taichu-ai/blob/master/docs/accelerator_metrics.md"
      notes: ""

    - id: ai_service_metrics
      description: "Provide a monitoring system capable of discovering and collecting metrics from workloads that expose them in a standard format (e.g. Prometheus exposition format)."
      level: MUST
      status: "Implemented"
      evidence:
        - "https://github.com/mensylisir/taichu-ai/blob/master/docs/ai_service_metrics.md"
      notes: ""

  security:
    - id: secure_accelerator_access
      description: "Ensure that access to accelerators from within containers is properly isolated and mediated by the Kubernetes resource management framework (device plugin or DRA) and container runtime, preventing unauthorized access or interference between workloads."
      level: MUST
      status: "Implemented"
      evidence:
        - "https://github.com/mensylisir/taichu-ai/blob/master/docs/secure_accelerator_access.md"
      notes: ""

  operator:
    - id: robust_controller
      description: "The platform must prove that at least one complex AI operator with a CRD (e.g., Ray, Kubeflow) can be installed and functions reliably. This includes verifying that the operator's pods run correctly, its webhooks are operational, and its custom resources can be reconciled."
      level: MUST
      status: "Implemented"
      evidence:
        - "https://github.com/mensylisir/taichu-ai/blob/master/docs/robust_controller.md"
      notes: ""
